name: automerge
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
